name: stroll
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova-regular.otf
        - asset: assets/fonts/proximanova-thin.otf
          weight: 200
        - asset: assets/fonts/proximanova-bold.otf
          weight: 700
